name: mgp2025_v4
channels:
- conda-forge
- anaconda
- defaults
dependencies:
  - jupyter
  - jupyterlab
  - seaborn
  - nomkl
  - openblas
  - watermark
  - pymc==4.3.0
  - arviz==0.13.0
  - aeppl==0.0.38
  - aesara==2.8.7
  - theano-pymc==1.1.2
  - tqdm
  - pip
  - pip:
    - daft
    - pgmpy
    - causalgraphicalmodels
     - watermark
     - "git+git://github.com/arviz-devs/arviz.git@main"
     - "git+git://github.com/pymc-devs/pymc.git@main"
     - causalgraphicalmodels
     - daft
